import React, {useEffect, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {api, usingRemoteApi} from './api'
import type {Lesson, Queue, Screen, Subject, User} from './types'
import './styles.css'

const statusCopy: Record<string,string> = {waiting:'Вы в очереди',next:'Вы следующий',called:'Вас вызывают',serving:'Обслуживание',completed:'Завершено'}
function App(){
 const [user,setUser]=useState<User|null>(null); const [auth,setAuth]=useState<'login'|'name'>('login'); const [screen,setScreen]=useState<Screen>('home'); const [lesson,setLesson]=useState<Lesson|null>(null); const [queue,setQueue]=useState<Queue|null>(null); const [lessons,setLessons]=useState<Lesson[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{ if(user){setLoading(true);Promise.all([api.getQueue(),api.getUniversitySchedule()]).then(([activeQueue, schedule])=>{setQueue(activeQueue);setLessons(schedule)}).catch(()=>setError('Не удалось загрузить расписание.')).finally(()=>setLoading(false))}},[user])
 const act=async(fn:()=>Promise<void>)=>{setLoading(true);setError('');try{await fn()}catch{setError('Не удалось загрузить данные.')}finally{setLoading(false)}}
 const login=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setLoading(true);setError('');try{const u=await api.login(String(f.get('group')),String(f.get('password')));setUser(u);setAuth('name')}catch(error){setError(error instanceof Error&&error.message==='INVALID_CREDENTIALS'?'Неверная группа или пароль.':'Не удалось выполнить вход.')}finally{setLoading(false)}}
 if(!user || auth==='name') return <main className="auth"><div className="brand"><div className="logo">L</div><h1>LabFlow</h1><p>Расписание лабораторных и электронная очередь.</p></div>{auth==='login'?<form onSubmit={login} className="panel"><label>Группа<input name="group" placeholder="Например, ИВТ-21" required/></label><label>Пароль<input name="password" type="password" placeholder="Введите пароль" required/></label><button disabled={loading}>{loading?'Выполняем вход…':'Войти'}</button>{error&&<p className="error">{error}</p>}</form>:<form className="panel" onSubmit={e=>{e.preventDefault();const n=String(new FormData(e.currentTarget).get('name')).trim();if(!n)return;act(async()=>{const u=await api.saveName(n,user!);setUser(u);setAuth('login')})}}><h2>Как вас зовут?</h2><p className="muted">Укажите имя, под которым к вам обращаться.</p><label>Имя<input name="name" autoFocus placeholder="Ваше имя" required/></label><button disabled={loading}>{loading?'Сохраняем…':'Продолжить'}</button></form>}</main>
 const openLesson=async(l:Lesson)=>{await act(async()=>setLesson(await api.getLesson(l.id)));setScreen('lesson')}
 const openQueue=async()=>{await act(async()=>setQueue(await api.getQueue()));setScreen('queue')}
 const join=async()=>{if(!lesson)return;await act(async()=>setQueue(await api.joinQueue(lesson.id)));setScreen('queue')}
 const leave=async()=>{if(confirm('Покинуть очередь? Вы потеряете своё место.')){await act(async()=>{await api.leaveQueue();setQueue(null);setScreen('lesson')})}}
 return <div className="app"><header><button className="wordmark" onClick={()=>setScreen('home')}><span className="logo small">L</span>LabFlow</button>{screen!=='home'&&<button className="back" onClick={()=>setScreen(screen==='lesson'?'schedule':screen==='queue'?'lesson':'home')}>Назад</button>}</header><div className="content">{error&&<div className="error banner">{error}<button onClick={()=>setError('')}>×</button></div>}{loading?<Skeleton/>:<>{screen==='home'&&<Home user={user} queue={queue} lessons={lessons} onQueue={openQueue} onLesson={openLesson}/>} {screen==='schedule'&&<ScheduleView lessons={lessons} onOpen={openLesson}/>} {screen==='lesson'&&lesson&&<LessonDetails lesson={lesson} queue={queue} onJoin={join} onQueue={openQueue}/>} {screen==='queue'&&<QueueView queue={queue} lesson={lesson} onLeave={leave}/>} {screen==='profile'&&<Profile user={user} onToggle={async()=>setUser(await api.toggleNotifications(user))} onHistory={()=>setScreen('history')}/>} {screen==='history'&&<History/>}</>}</div><nav><button className={screen==='home'?'active':''} onClick={()=>setScreen('home')}>⌂<span>Главная</span></button><button className={screen==='schedule'?'active':''} onClick={()=>setScreen('schedule')}>▤<span>Расписание</span></button><button className={['profile','history'].includes(screen)?'active':''} onClick={()=>setScreen('profile')}>◯<span>Профиль</span></button></nav></div>
}
const Skeleton=()=> <div className="skeleton"><i/><i/><i/><i/></div>
function Home({user,queue,lessons,onQueue,onLesson}:{user:User;queue:Queue|null;lessons:Lesson[];onQueue:()=>void;onLesson:(l:Lesson)=>void}){const upcoming=lessons.find(lesson=>!isPastDate(lesson.date));return <><section className="hero"><p className="eyebrow">ДОБРЫЙ ДЕНЬ</p><h1>Привет, {user.name} 👋</h1><p className="muted">{user.group}</p></section>{queue&&<button className="queue-card" onClick={onQueue}><div><p className="eyebrow">ВАША ОЧЕРЕДЬ</p><strong>№{queue.number}</strong><p>{queue.peopleAhead} впереди · ~{queue.estimatedWaitMinutes} мин</p></div><span>Открыть очередь →</span></button>}<div className="section-title"><h2>Ближайшие</h2><span className="muted">Из расписания университета</span></div>{upcoming?<button className="lesson-card" onClick={()=>onLesson(upcoming)}><div><h3>{upcoming.subjectId==='programming'?'Программирование':'Лабораторная'}</h3><p>{upcoming.title.replace('Laboratory','Лабораторная')}</p></div><time>{upcoming.date==='Today'?'Сегодня':upcoming.date}<br/><b>{upcoming.startTime}</b></time></button>:<div className="hint">Ближайших лабораторных пока нет.</div>}{!queue&&<div className="hint">Активная очередь появится здесь.</div>}</>}
const Subjects=({items,onOpen}:{items:Subject[];onOpen:(s:Subject)=>void})=><><h1>Предметы</h1><p className="muted">Выберите предмет, чтобы увидеть лабораторные.</p><div className="list">{items.map(s=><button className="list-card" key={s.id} onClick={()=>onOpen(s)}><span><b>{s.name==='Programming'?'Программирование':s.name==='Physics'?'Физика':'Математика'}</b><small>{s.labCount} лабораторных</small></span><span>→</span></button>)}</div></>
const Schedule=({subject,lessons,onOpen}:{subject:Subject;lessons:Lesson[];onOpen:(l:Lesson)=>void})=><><h1>{subject.name==='Programming'?'Программирование':subject.name==='Physics'?'Физика':'Математика'}</h1><p className="muted">Расписание лабораторных</p><p className="date-label">СЕНТЯБРЬ</p><div className="list">{lessons.map(l=><button className={'list-card lesson-row '+(l.registration==='completed'?'dim':'')} key={l.id} onClick={()=>onOpen(l)}><span><b>{l.title.replace('Laboratory','Лабораторная')}</b><small>{l.date==='Today'?'Сегодня':l.date} · {l.startTime}–{l.endTime}</small></span><span className={'tag '+l.registration}>{l.registration==='open'?'Открыта':l.registration==='not_open'?'Скоро':'Закрыта'}</span></button>)}</div></>
const LessonDetails=({lesson,queue,onJoin,onQueue}:{lesson:Lesson;queue:Queue|null;onJoin:()=>void;onQueue:()=>void})=><><p className="eyebrow">{lesson.subjectId==='programming'?'ПРОГРАММИРОВАНИЕ':'ЛАБОРАТОРНАЯ'}</p><h1>{lesson.title.replace('Laboratory','Лабораторная')}</h1><p className="muted">{lesson.date==='Today'?'Сегодня':lesson.date} · {lesson.startTime}–{lesson.endTime}</p><div className="detail-card"><p>Преподаватель <b>{lesson.teacher||'—'}</b></p><p>Аудитория <b>{lesson.room||'—'}</b></p><p>Регистрация <b>{lesson.registration==='open'?'Открыта':lesson.registration==='not_open'?'Ещё не открыта':'Закрыта'}</b></p></div>{queue?<button onClick={onQueue}>Открыть очередь</button>:lesson.registration==='open'?<button onClick={onJoin}>Встать в очередь</button>:<button disabled>{lesson.registration==='not_open'?'Регистрация ещё не открыта':'Регистрация закрыта'}</button>}</>
const QueueView=({queue,lesson,onLeave}:{queue:Queue|null;lesson:Lesson|null;onLeave:()=>void})=><>{queue?<><p className="eyebrow">{statusCopy[queue.status].toUpperCase()}</p><h1>{lesson?.title?.replace('Laboratory','Лабораторная')||'Ваша очередь'}</h1><p className="muted">{lesson?.date==='Today'?'Сегодня':lesson?.date||'Сегодня'} · {lesson?.startTime||'14:30'}</p><div className={'queue-main '+queue.status}><p>{statusCopy[queue.status]}</p><strong>№{queue.number}</strong><div className="queue-stats"><span><b>{queue.peopleAhead}</b>впереди</span><span><b>~{queue.estimatedWaitMinutes} мин</b>ожидание</span></div></div>{queue.status!=='completed'&&<button className="secondary" onClick={onLeave}>Покинуть очередь</button>}</>:<div className="empty"><h2>Нет активной очереди</h2><p>Встаньте в очередь на лабораторную, чтобы увидеть здесь свою позицию.</p></div>}</>
const Profile=({user,onToggle,onHistory}:{user:User;onToggle:()=>void;onHistory:()=>void})=><><h1>Профиль</h1><div className="profile-card"><p>Имя<b>{user.name}</b></p><p>Группа<b>{user.group}</b></p></div><button className="list-card" onClick={onToggle}><span><b>Уведомления</b><small>Обновления очереди и вызовы</small></span><span className="toggle">{user.notifications?'Вкл.':'Выкл.'}</span></button><button className="list-card" onClick={onHistory}><span><b>История</b></span><span>→</span></button></>
const History=()=> <><h1>История</h1><div className="list"><div className="history-item"><b>Программирование</b><p>Лабораторная №2</p><small>12 сентября · 14:30</small><span className="tag completed">Завершено</span></div></div></>
const dateKey=(value:string)=>{const match=value.match(/^(\d{2})\.(\d{2})\.(\d{4})$/);return match?`${match[3]}-${match[2]}-${match[1]}`:value}
const isPastDate=(value:string)=>{if(value==='Today'||value==='Сегодня')return false;const raw=value.trim();const key=dateKey(raw).slice(0,10);const parsed=new Date(`${key}T23:59:59`);return !Number.isNaN(parsed.getTime())&&parsed.getTime()<Date.now()}
const dateLabel=(value:string)=>{if(value==='Today'||value==='Сегодня')return 'Сегодня';const key=dateKey(value);const parsed=new Date(`${key}T00:00:00`);return Number.isNaN(parsed.getTime())?value:new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(parsed)}
const ScheduleView=({lessons,onOpen}:{lessons:Lesson[];onOpen:(l:Lesson)=>void})=>{const visibleLessons=lessons.filter(lesson=>!isPastDate(lesson.date));const groups=visibleLessons.reduce<Record<string,Lesson[]>>((acc,lesson)=>{(acc[dateKey(lesson.date)]??=[]).push(lesson);return acc},{});const dates=Object.keys(groups).sort();return <><p className="eyebrow">ИЗ РАСПИСАНИЯ УНИВЕРСИТЕТА</p><h1>Расписание</h1><p className="muted">{usingRemoteApi?'Данные загружаются через API университета':'Сейчас показана локальная заглушка'}</p>{visibleLessons.length?dates.map(date=><section className="schedule-day" key={date}><p className="date-label">{dateLabel(date)}</p><div className="list">{groups[date].sort((a,b)=>a.startTime.localeCompare(b.startTime)).map(l=><button className="list-card lesson-row" key={l.id} onClick={()=>onOpen(l)}><span><b>{l.subject || (l.subjectId==='programming'?'Программирование':'Лабораторная')}</b><small>{l.title.replace('Laboratory','Лабораторная')}{l.note?` · ${l.note}`:''}</small></span><span><b>{l.startTime}</b><small>{l.endTime}{l.registration==='open'?' · Открыта':''}</small></span></button>)}</div></section>):<div className="hint">Предстоящих лабораторных пока нет.</div>}</>}
createRoot(document.getElementById('root')!).render(<App/>)
